### ISSUE TITLE
Running the image on WSL2

### ISSUE THREAD

**Issue by mstory89** [LCAS/LCASTOR#23]
The TIAGO tutorial demos (which require nvidia-docker2 as well) run fine. No issues until running the image which gives the following error: 

~$ docker run lcas.lincoln.ac.uk/lcastor/lcastor_base:latest

/bin/bash: /home/lcastor/ros_ws/src/LCASTOR/lcastor_docker/entrypoint.sh: No such file or directory

**Comment by pulver22** [comment]
Sorry @mstory89 but did you `git clone` this repository? You need to enter the `lcastor_docker` of this repository before launching `.run_docker.sh`.

**Comment by mstory89** [comment]
I see what I have done. I git cloned through VS Code which had the default terminal as 18.04. Cloned on my 20.04 terminal and problem solved
