### ISSUE TITLE
Docker image doesn't contain tiago dependency

### ISSUE THREAD

**Issue by pulver22** [LCAS/LCASTOR#6]

**Comment by Melanoneiro** [comment]
Hi, which ones are those? [tiago-robot](https://github.com/pal-robotics/tiago_robot) and [tiago-navigation](https://github.com/pal-robotics/tiago_navigation)?

**Comment by pulver22** [comment]
Everything listed [here](http://wiki.ros.org/Robots/TIAGo/Tutorials/Installation/InstallUbuntuAndROS). I am finalising the dockerfile and I will open a new PR soon. So please leave it with me ;)

**Comment by francescodelduchetto** [comment]
I think this is solved by the merge of #8
